In [26]:
print("hello")

hello

Step 1: Data Exploration & Leading

In [27]:
#importing dependencies

import pandas as pd
#mysql toolkit
import pymysql #this work as adapter
from sqlalchemy import create_engine

In [28]:
df=pd.read_csv('Walmart.csv',encoding_errors='ignore')
df.shape

(10051, 11)

In [29]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [30]:
df.describe()

         invoice_id      quantity        rating  profit_margin
count  10051.000000  10020.000000  10051.000000   10051.000000
mean    5025.741220      2.353493      5.825659       0.393791
std     2901.174372      1.602658      1.763991       0.090669
min        1.000000      1.000000      3.000000       0.180000
25%     2513.500000      1.000000      4.000000       0.330000
50%     5026.000000      2.000000      6.000000       0.330000
75%     7538.500000      3.000000      7.000000       0.480000
max    10000.000000     10.000000     10.000000       0.570000

In [31]:
#All duplicated items are counted
df.duplicated().sum()

np.int64(51)

In [32]:
df.drop_duplicates(inplace=True)

In [33]:
df.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [34]:
#dropping all the rows with missing records of quantity and unit price
df.dropna(inplace=True)

In [35]:
df.dtypes

invoice_id          int64
Branch                str
City                  str
category              str
unit_price            str
quantity          float64
date                  str
time                  str
payment_method        str
rating            float64
profit_margin     float64
dtype: object

In [36]:
df['unit_price'].astype(float)#here we got error coz there is $ sign present thats why we cant so we have to deal with that first

ValueError: could not convert string to float: '$74.69'

In [ ]:
df['unit_price']=df['unit_price'].str.replace('$','').astype(float)
df.head()

In [ ]:
#here we make a new coloum of Total which will tell us total amount
df['total']=df['unit_price']*df['quantity']
df.head()

In [ ]:
df.info()
df.to_csv('walmart_clean_data.csv',index=False)
df.columns=df.columns.str.lower()

<class 'pandas.DataFrame'>
Index: 9969 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      9969 non-null   int64
 1   branch          9969 non-null   str
 2   city            9969 non-null   str
 3   category        9969 non-null   str
 4   unit_price      9969 non-null   str
 5   quantity        9969 non-null   float64
 6   date            9969 non-null   str
 7   time            9969 non-null   str
 8   payment_method  9969 non-null   str
 9   rating          9969 non-null   float64
 10  profit_margin   9969 non-null   float64
dtypes: float64(3), int64(1), str(7)
memory usage: 934.6 KB

In [ ]:
#mysql connection
engine_mysql=create_engine("mysql+pymysql://root:1234@127.0.0.1:3306/Walmart_db")
try:
    engine_mysql
    print("Connected succesfuly")
except:
    print("no Connection made")

Connected succesfuly

In [39]:
df.to_sql(name='walmart',con=engine_mysql,if_exists='append',index=False)

OperationalError: (pymysql.err.OperationalError) (1049, "Unknown database 'walmart_db'")
(Background on this error at: https://sqlalche.me/e/20/e3q8)